/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.radd.view;

import io.github.radd.controller.NoteController;
import io.github.radd.model.NoteModel;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Utilities;

/**
 *
 * @author Piotr
 */
public class MainFrame extends javax.swing.JFrame implements Observer {

    private NoteController controller;
    private NoteModel model;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    
    public MainFrame(NoteController c, NoteModel m) {
        controller = c;
        model = m;
        
        //Add observer (this view) to model
        ((Observable) model).addObserver(this);
        
        initComponents();
        initAfter();
    }
    
    private void initAfter() {
        setTitle("Notepad");
        defaultTheme();
    }
    
    public void showView() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        docScrollPane = new javax.swing.JScrollPane();
        docTextPane = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        docScrollPane.setBorder(null);

        docTextPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 4, 4, 3));
        docTextPane.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        docTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        docTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                docTextPaneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                docTextPaneKeyReleased(evt);
            }
        });
        docScrollPane.setViewportView(docTextPane);

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        viewMenu.setText("View");

        jCheckBoxMenuItem1.setText("Dark theme");
        jCheckBoxMenuItem1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem1ItemStateChanged(evt);
            }
        });
        viewMenu.add(jCheckBoxMenuItem1);

        menuBar.add(viewMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(docScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(docScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        openFile();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void docTextPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docTextPaneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("enter is pressed");
            if(insertTabs())
                evt.consume();
        }
    }//GEN-LAST:event_docTextPaneKeyPressed

    private void jCheckBoxMenuItem1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
           darkTheme();
        else
           defaultTheme();
    }//GEN-LAST:event_jCheckBoxMenuItem1ItemStateChanged
 
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        saveFile();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void docTextPaneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docTextPaneKeyReleased
        controller.updateFileContent(docTextPane.getText());
    }//GEN-LAST:event_docTextPaneKeyReleased
    
    
    private void saveFile() {
        controller.saveFile();
    }
    
    private  void darkTheme() {
        docTextPane.setBackground(new java.awt.Color(68, 68, 68));
        docTextPane.setForeground(new java.awt.Color(255, 255, 255));
        docTextPane.setCaretColor(new java.awt.Color(255, 255, 255));
        docTextPane.updateUI(); 
    }
    
    private  void defaultTheme() {
        docTextPane.setBackground(new java.awt.Color(255, 255, 255));
        docTextPane.setForeground(new java.awt.Color(0, 0, 0));
        docTextPane.setCaretColor(new java.awt.Color(0, 0, 0));
        docTextPane.updateUI();
    }
    
    //TODO new class
    //TODO add also spaces
    private boolean insertTabs() {
        String text = docTextPane.getText() + " "; //Add space because last chars are \r\n  and split() do not split it to new line
        String[] lines = text.split(System.lineSeparator());
        if(lines.length == 0)
            return false;
        
        int caretPos = docTextPane.getCaretPosition();
        int currRow = (caretPos == 0) ? 1 : 0;
        
        try {
            for (int offset = caretPos; offset > 0;) {
                offset = Utilities.getRowStart(docTextPane, offset) - 1;
                currRow++;
            }
        } catch (BadLocationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String currLine = lines[currRow - 1];
        StringBuilder sb = new StringBuilder();
        for (char c : currLine.toCharArray()) {
            if("\t".equals(""+c))
                sb.append("\t");
            else 
                break;
        } 
        
        if(sb.length() > 0) {
            try {
                docTextPane.getStyledDocument().insertString(
                        caretPos, System.lineSeparator() + sb, null);
            } catch (BadLocationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            return true;
        }
        else
            return false;
    }
    
    private void openFile() {
        String path = model.getOpenFilePath();
        JFileChooser chooser = new JFileChooser(path);
	chooser.setFileFilter(model.getFileFilter());
        chooser.setAcceptAllFileFilterUsed(false);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            controller.setFile(chooser.getSelectedFile());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane docScrollPane;
    private javax.swing.JTextPane docTextPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void update(Observable o, Object arg) {
        NoteModel.Action action = (NoteModel.Action) arg;
        System.out.println("update: " + action);
        
        switch(action) {
            case OPEN_FILE: showFile(); break;
            case OPEN_ERROR: showErrorMessage(model.getErrorMsg()); break;
            case SAVE_NEW_FILE: saveNewFile(); break;
        }
    }
    
    private void showErrorMessage(String msg) {
        JOptionPane.showMessageDialog(this,
                msg,
                "Error",
                JOptionPane.ERROR_MESSAGE); 
    }

    private void showFile() {
        docTextPane.setText(model.getFileContent());
        
        //Scroll to top
        docTextPane.setCaretPosition(0);  
    }

    private void saveNewFile() {
        String path = model.getSaveFilePath();
        JFileChooser chooser = new JFileChooser(path);
	chooser.setFileFilter(model.getFileFilter());
        chooser.setAcceptAllFileFilterUsed(false);
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            controller.saveFile(chooser.getSelectedFile());
        }
    }
    
    
}
